### ISSUE TITLE
unresolved import rgb::validation::TxResolverError

### ISSUE THREAD

**Issue by Goosie** [mycitadel/mycitadel-node#1]
Trying to follow the demo of the mycitadel wallet by watching https://www.youtube.com/watch?v=d0MjmcCmegs&feature=youtu.be

I get an error after git-clone and the installation command: cargo install --path .

error[E0432]: unresolved import rgb::validation::TxResolverError
--> /home/perry/.cargo/git/checkouts/rgb-node-c848531e1d8697c8/520bfc5/src/stashd/electrum.rs:19:35
|
19 | use rgb::validation::{TxResolver, TxResolverError};
| ^^^^^^^^^^^^^^^
| |
| no TxResolverError in validation
| help: a similar name exists in the module: TxResolver

error[E0412]: cannot find type TxResolverError in module validation
--> /home/perry/.cargo/git/checkouts/rgb-node-c848531e1d8697c8/520bfc5/src/stashd/runtime.rs:361:57
|
361 | ) -> Result<Option<(Transaction, u64)>, validation::TxResolverError> {
| ^^^^^^^^^^^^^^^ help: a trait with a similar name exists: TxResolver
|
::: /home/perry/.cargo/git/checkouts/descriptor-wallet-811041b0e5aa9809/e39f6f3/src/resolvers/mod.rs:90:1
|
90 | pub trait TxResolver {
| -------------------- similarly named trait TxResolver defined here

... build failed.
What could goes wrong here?

**Comment by dr-orlovsky** [comment]
This was fixed few commits ago, so
1) make sure you are using the latest master tip (do `git pull`)
2) if this will not help, try `cargo update`
3) if this will not help, try `cargo clean`
4) try `cargo build --all-features` and run `./target/debug/mycitadel` instead of just `mycitadel`

**Comment by dr-orlovsky** [comment]
It was caused by the fact that Electrum transaction resolver was moved from `rgb-core` into `descriptor-wallet` lib, so you basically need to update upstream dependencies to the latest version. `Cargo.lock` already updated, so this is really strange that it fails to build - most likely you are not using the latest master

**Comment by Goosie** [comment]
Unfortunately this did not work.
Did git pull, cargo update, cargo clean, cargo build --all-features than I get in the beginning already a warning:
arning: Patch `lightning-invoice v0.3.0 (https://github.com/LNP-BP/rust-lightning-invoice?tag=systemtime-fix#979dce95)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.

  Compiling rgb_node v0.4.0-alpha (https://github.com/rgb-org/rgb-node#520bfc50)
   Compiling mycitadel v0.1.0-beta (/home/perry/mycitadel-node)
error[E0432]: unresolved import `rgb::validation::TxResolverError`
  --> /home/perry/.cargo/git/checkouts/rgb-node-c848531e1d8697c8/520bfc5/src/stashd/electrum.rs:19:35
   |
19 | use rgb::validation::{TxResolver, TxResolverError};
   |                                   ^^^^^^^^^^^^^^^
   |                                   |
   |                                   no `TxResolverError` in `validation`
   |                                   help: a similar name exists in the module: `TxResolver`

**Comment by Goosie** [comment]
I'm on ubuntu 20:04

**Comment by Goosie** [comment]
Oke removed the directory did a clone again, than cargo build --all-features
No errors anymore. Lets go to the next step :-)

**Comment by dr-orlovsky** [comment]
Sometimes cargo is just crazy & indeterministic
